"""add duration and uix

Revision ID: b027d99c3d0a
Revises: 001
Create Date: 2026-05-06 05:14:16.466856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b027d99c3d0a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_sessions', sa.Column('duration_minutes', sa.Integer(), server_default='0', nullable=False))
    op.create_unique_constraint('uix_station_start', 'charging_sessions', ['station_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_station_start', 'charging_sessions', type_='unique')
    op.drop_column('charging_sessions', 'duration_minutes')
    # ### end Alembic commands ###
